### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticSignup#11]
Right now docs are duplicated between the readme and the MW.org page, with the readme being incomplete and MW.org being out of date

**Comment by kghbln** [comment]
I just updated the extensions page on mw.o, meaning that I removed all the stuff there except for the "Getting started" section which still needs to be moved to the README here. The rest seem to already be in a file within this repo.

**Comment by kghbln** [comment]
This is not just about unifying documentation but also about initially creating documentation. However, I cannot be of further help here. I am just getting the summary field when trying to use the {{#signupfields:}} parser function within a form. I will probably ask on the mailing list after the release and go from there.

**Comment by mwjames** [comment]
@toniher Can you help out here with a simple form that you used to check the `{{#signupfields:}}` functionality?

**Comment by toniher** [comment]
Sure, below a simple example:

<pre>
<noinclude>
This is the "User" form.
To create a page with this form, enter the page name below;
if a page with that name already exists, you will be sent to a form to edit that page.
{{#forminput:form=User}}
</noinclude><includeonly>
<div id="wikiPreview" style="display: none; padding-bottom: 25px; margin-bottom: 25px; border-bottom: 1px solid #AAAAAA;"></div>
{{#signupfields:}}
{{{for template|Institution}}}
{| class="formtable"
! Institution: 
| {{{field|Institution|rows=3|mandatory}}}
|}
{{{end template}}}
{{{standard input|save}}}{{{standard input|cancel}}}
</includeonly>
</pre>

**Comment by kghbln** [comment]
That's how you do it? I would probably never have guessed since this seem to be too simple. Will give it a shot later today.

**Comment by mwjames** [comment]
OK, here is what I got (after https://github.com/SemanticMediaWiki/SemanticSignup/commit/164576fcc70cb0c97f97cf58c6a0901022ffae10):

```
$egSemanticSignupSettings['formName'] = 'UserSignupForm';
$egSemanticSignupSettings['botName'] = '...'; //Existing user with "createaccount" rights
```

Form:UserSignupForm

```
<includeonly>{{#signupfields:}}{{{for template|UserSignup}}}
{| class="formtable"
! Institution: 
| {{{field|Institution|rows=3|mandatory}}}
|}
{{{end template}}}

{{{standard input|save|label=Create account}}}{{{standard input|cancel}}}</includeonly>
```

Template:UserSignup

```
<includeonly>[[Institution::{{{Institution|}}}]]</includeonly>
```

then go to "Create account" and ...

**Comment by kghbln** [comment]
As I realise now I had apart from incorrectly using the signupfields parser function another issue. There was a typo in the form's and template's name causing the failure on my side.

**Comment by kghbln** [comment]
Done this commit https://github.com/SemanticMediaWiki/SemanticSignup/commit/ae00c94caf1e5403fac760a78201d98c901a45b1 to fluff things up. The rest would be tweaks I guess. Thanks to @mwjames and @toniher
