### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by 3blake7** [SemanticMediaWiki/SemanticSignup#25]
I have latest MW, SMW, and SF

When I enable SS, I can create signup form, goto page while logged in but I get error on page while anon. It's really read, the error message refers to other extensions, which I comment out and just get another error with another extension. If I unset the form variable, it goes away.

First it's Fatal error: Call to a member function isAllowed() on a non-object in for AdminLinks
Fatal error: Call to a member function isAnon() on a non-object in for LiquidThreads

Please help, thanks!

**Comment by JeroenDeDauw** [comment]
@yaronkoren any idea?

**Comment by mwjames** [comment]
> I have latest MW, SMW, and SF

Means exactly what? (Version numbers would be nice)

> First it's Fatal error: Call to a member function isAllowed() on a non-object in for AdminLinks
> Fatal error: Call to a member function isAnon() on a non-object in for LiquidThreads

This isn't really sufficient to make any guess on what is going wrong. Please have a look at [0] to provide a full stack trace. That said, given the mentioned `isAnon`/ `isAllowed` may refer to `User::isAllowed` / `User::isAnon` but this is just a conjecture.

[0] https://semantic-mediawiki.org/wiki/Help:Identifying_bugs

**Comment by 3blake7** [comment]
MW 1.25.1 SMW 2.2.1 SF 3.2 SS 1.0

It only happened when logged out on Special:SemanticSignup

@mwjames all those settings made no difference, no stack trace or anything came up

**Comment by 3blake7** [comment]
I also sometimes get a proxy error, but only on that page and not every time.

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /index.php/Special:SemanticSignup.

Reason: Error reading from remote server

**Comment by mwjames** [comment]
> It only happened when logged out on Special:SemanticSignup
> made no difference, no stack trace or anything came up

If you have settings like below you should have some kind of trace for the fatal/exception either in MW or PHP log.

```
error_reporting(E_STRICT|E_ALL);
ini_set("display_errors", 1);
$wgShowExceptionDetails = true;
$wgDevelopmentWarnings = false;
$wgShowSQLErrors = true;
$wgDebugDumpSql  = false;
$wgShowDBErrorBacktrace = true;
```

Without a trace it is impossible to narrow down the issue and yet let alone to propose a fix (well I'm guessing something changed in 1.25 which makes `Special:SemanticSignup` going rogue).

**Comment by 3blake7** [comment]
http://wiki.fractalfederation.com/index.php/Special:SemanticSignup
http://wiki.fractalfederation.com/index.php/Special:Version

The stack trace just isn't coming up, even with those settings. Sorry I can't provide more. It's really weird.
