### ISSUE TITLE
Remove depreciated "wfMsg"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticSignup#3]
https://github.com/SemanticMediaWiki/SemanticSignup/search?utf8=%E2%9C%93&q=wfMsg+
Will tackle this tomorrow together with the SWL stuff.

**Comment by mwjames** [comment]
Should be fixed maybe after #2 has been merged.

**Comment by kghbln** [comment]
Indeed! Will wait for this.

**Comment by mwjames** [comment]
Now its your turn ;-)

**Comment by kghbln** [comment]
I knew this would happen. :) It's late today though. Will try to does something useful tomorrow.

**Comment by JeroenDeDauw** [comment]
> It's late today though.

23:58 is late? Pfft, it's 2 whole minutes away from midnight!

**Comment by mwjames** [comment]
If possible it would be brill to have the `SemanticSignup.i18n.aliases.php` and magic file moved into the i18n folder (not sure if tn.w is involved in this).

**Comment by kghbln** [comment]
> If possible it would be brill to have the `SemanticSignup.i18n.aliases.php` and magic file moved into the i18n folder (not sure if tn.w is involved in this).

Cannot tell if this is possible without breaking the translation process. I asked at [i18n on mw.o](https://www.mediawiki.org/wiki/Talk:Localisation#Location_of_.22alias.22_and_.22namespaces.22)

**Comment by kghbln** [comment]
I created pull request https://github.com/SemanticMediaWiki/SemanticSignup/pull/4 @siebrand Hope that I learned a bit from the SWL disaster last June.

**Comment by kghbln** [comment]
@Nikerabbit Siebrand currently does not seem to be available due to holidays? Well, good on him if that's the case! May you perhaps do the honours and have a quick walk-trough? Will be cool!

**Comment by siebrand** [comment]
I've reviewed the referenced pull request #4. Does that mean that open items for me are dealt with?

**Comment by kghbln** [comment]
Yeah, this is it for this extension. There is another little resistor at another extension. Will ping you there. Thanks for the encouragement and review!
