### ISSUE TITLE
Create 1.0 release

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticSignup#6]
Blockers:
- #11 - Unify documentation
- #12 - Update release notes

Having confirmation that everything is fluff from at least one user would be nice as well.

**Comment by JeroenDeDauw** [comment]
@mwjames @kghbln

**Comment by mwjames** [comment]
- [x] @toniher #10 and to confirm that it works.

**Comment by JeroenDeDauw** [comment]
@SemanticMediaWiki/testers testing of this extension for regressions compared to the previous release is appreciated. You can get the dev version of 1.0 as follows:

```
composer require mediawiki/semantic-signup:~1.0@dev
```

**Comment by mwjames** [comment]
@toniher @jchapin Do see any immediate issues that would stop use putting a 1.0.0 release tag on the current master?

**Comment by toniher** [comment]
I must apologise, https://github.com/SemanticMediaWiki/SemanticSignup/pull/13, $wgOut could not be avoided so easily

**Comment by mwjames** [comment]
> I must apologise, #13, $wgOut could not be avoided so easily

No need for apologies, I'm glad you are trying to solve this issue.

**Comment by kghbln** [comment]
I would like to test this extension however there are no instructions how to actually use it. Could anybody post an example form. I feel like I have to reinvent the wheel here. Use {{#signupfields:}}? So what?

**Comment by kghbln** [comment]
I am sorry for my last post. I am very grumpy today and not getting this to work did not help the cause. Expecting this to be a on-the-fly thing did not help either. I will now stop hijacking this thread [-seriously](https://semantic-mediawiki.org/wiki/User:Kghbln/Sirius)!

**Comment by kghbln** [comment]
- [x] @kghbln #11

**Comment by JeroenDeDauw** [comment]
The release notes are still empty - I'm guessing something actually did happen between 0.4 and 1.0? :)

**Comment by kghbln** [comment]
Well there was a wild "0.5". will add.

**Comment by kghbln** [comment]
@JeroenDeDauw Guess you got what you wanted. ;)

**Comment by JeroenDeDauw** [comment]
Everyone fine with making the 1.0 rel?

**Comment by mwjames** [comment]
I'd say go ahead, I have seen it work for the examples cited which means it does what is advertised. The code isn't pretty but that's another topic.

**Comment by JeroenDeDauw** [comment]
Done
