### ISSUE TITLE
signupfields parser function seems not to work

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticSignup#7]
Hi, I don't know whether this may be still in development, but I was trying to make it work and I noticed that  {{#signupfields:}} is not being parsed (neither in Main Page nor inside Form page)

I tried in MW 1.23.3, SMW 2.1, SF 2.8

**Comment by mwjames** [comment]
Would be good if you could debug this because I don't have SF installed.

**Comment by toniher** [comment]
Hi, I'm struggling with it. Hook is there, but function seems not to be called. I would let you know...

**Comment by mwjames** [comment]
Solved with 30b6856823 but I'm not sure how `{{#signupfields:}}` is actually used.

**Comment by toniher** [comment]
Thanks! I can continue debugging from that point now!
