### ISSUE TITLE
Issue rendering signup form

### ISSUE THREAD

**Issue by toniher** [SemanticMediaWiki/SemanticSignup#9]
In UserFieldsCreateTemplate.php _execute_ method the following code:

```
            if ( !$this->haveData( 'header' ) ) {
                  return '';
            }
```

prevents form to be drawn.
If commented, everything OK. However, I noticed that Javascript checks (such as mandatory acting on empty fields) do not seem to work, so something should be included to make it happen. Any idea is appreciated.

**Comment by mwjames** [comment]
Maybe try `@$this->haveData( 'header' ) === false` in order to prevent `$this->html( 'header' )` from accessing a non-existing header.

>  I noticed that Javascript checks (such as mandatory acting on empty fields) do not seem to work, so something should be included to make it happen. Any idea is 

JavaScript from SF? Try loading/register the SF resourcemodule with this template. (maybe something like `$this->getSkin()->getOutput()->addModules( ... );`

**Comment by toniher** [comment]
Sorry not reading fully your comment first. I just submitted pull request https://github.com/SemanticMediaWiki/SemanticSignup/pull/10. I cannot access Skin object from $this, so I had to use global $wgOut :/. I removed header reference as well.

**Comment by mwjames** [comment]
Once you get this rolling maybe you could make one or two screen-dumps (see [SG](https://www.semantic-mediawiki.org/wiki/SG) or [SIL](https://www.semantic-mediawiki.org/wiki/SIL)) as it will be easier for users to actually anticipate what this extension can do.

**Comment by toniher** [comment]
No problem. Right now extension is a bit spartan, and a next step would be offering a better look and options such as 'password by email' (as it's the case with default signup)

![semantic-signup](https://cloud.githubusercontent.com/assets/535539/6044403/4eedfd0e-ac93-11e4-879b-2a9d898f23f1.png)

**Comment by mwjames** [comment]
The screen-dump has been added to smw.org@SES

> Right now extension is a bit spartan, and a next step would be offering a better look and options such as 'password by email' (as it's the case with default signup)

Maybe it is best to convert those items into follow-ups.

**Comment by kghbln** [comment]
follow-up for "password by email": see issue https://github.com/SemanticMediaWiki/SemanticSignup/issues/15
